
export const robot = [
    {
        id:1,
        name:'Sudu',
        email:'sudueeee@gmail.com'
    },
    {
        id:2,
        name:'Supokudu',
        email:'sudusas@gmail.com'
    },
    {
        id:3,
        name:'kuku',
        email:'sudasasasasasu@gmail.com'
    },
    {
        id:4,
        name:'kuku',
        email:'sudasasasasasu@gmail.com'
    },
    {
        id:5,
        name:'kuku',
        email:'sudasasasasasu@gmail.com'
    },
    {
        id:6,
        name:'kuku',
        email:'sudasasasasasu@gmail.com'
    },
    {
        id:7,
        name:'kuku',
        email:'sudasasasasasu@gmail.com'
    },
    {
        id:8,
        name:'kuku',
        email:'sudasasasasasu@gmail.com'
    },
    {
        id:9,
        name:'kuku',
        email:'sudasasasasasu@gmail.com'
    },
];
